### ISSUE TITLE
with watermark don't work

### ISSUE THREAD

**Issue by hamaz562006** [TufayelLUS/TikTok-Video-Downloader-PHP#15]
Access to v19-web-newkey.tiktokcdn.com was denied

https://v16-web-newkey.tiktokcdn.com/5c8801735eeb489ad3c0b2af7010aec5/5f6d9749/video/tos/alisg/tos-alisg-pve-0037/2ee73819ae364f6f989c058a40763879/?a=1988&br=3656&bt=1828&cr=0&cs=0&cv=1&dr=0&ds=3&er=&l=202009250107420101151510441819C37F&lr=tiktok_m&mime_type=video_mp4&qs=0&rc=M2h2b3A4aXc4dzMzOTczM0ApNzo3NDg7aDs5NzZlNThnZGdhc2lnZG9hNF9fLS1fMTRzczNjLmAxMjIwMmM0YDRgYl46Yw%3D%3D&vl=&vr=

**Comment by TufayelLUS** [comment]
Hi @hamaz562006 ,
I am concerned about this issue and it is happening due to a problem in HTTP REFERER while making a request to download the video. The only solution to this is self-hosting the videos which I added in the source code just now. Kindly use the source code to be able to download and host videos locally (watermarked videos only). Thank you.
