### ISSUE TITLE
videos are not downloading

### ISSUE THREAD

**Issue by jaimin2000** [TufayelLUS/TikTok-Video-Downloader-PHP#17]
can successfully fetch videos but can not download

**Comment by TufayelLUS** [comment]
Thank you for letting me know. I will have a look at the issue and update the repository as soon as the issue is solved.

**Comment by jaimin2000** [comment]
do you have any source to get a solution or you are doing it yourself? if you can share it with me then I can solve it myself and can merge with your repo.

**Comment by TufayelLUS** [comment]
I tried to debug the issue, it is probably related to the cookies as I tried to download the video using python and it worked well with cookies being set. If you can inject cookies into the downloadVideo function, it should start to work again.

**Comment by jaimin2000** [comment]
on your website https://www.novice-geek.com/tiktok.php, I inserted TikTok video URL and try to download the video and it is redirected me to another tab, and try to load the video, but actually, the problem is with the video file.

**Comment by jaimin2000** [comment]
can you share me that python repo URL, so i can check with that.

**Comment by TufayelLUS** [comment]
I don't have any python version of the script at this moment. I did that just to perform some tests. I retested again and seems like my python code also fails to do so. Actually, the website is returning 403 access denied error when PHP CURL is trying to fetch the video. As the video is not downloading, the window is failing to play the video as the video bytes are not downloaded into the file created.

**Comment by jaimin2000** [comment]
i have a plugin which is fetching non watermarked videos

**Comment by timeceeper** [comment]
Hi,
since a few days the download doesnt work anymore.
All mp4 files has html-content.  Access Denied (380 bytes)

**Comment by TufayelLUS** [comment]
Hi @timeceeper 
Yes, I have also checked the issue. Seems like TikTok made some changes that don't allow access to watermarked video even with HTTP referer. I am still working on it to find out a fix to the problem. I will update the code as soon as I fix it.

**Comment by TufayelLUS** [comment]
I have tried to look into other public repositories, but most of them use 3rd party API for downloading videos which isn't the purpose of my repository here. And there isn't any single public repository that is up to date so that I can get any clue of this download error.
From my observation of the issue so far,
1. Tiktok isn't allowing access to watermarked video(that's the only source, for now, to get video ID for the watermark free api) even with HTTP referer
2. I suspected that the problem is now with the cookie. I tried to use the existing device cookie and injected it into my CURL request. But it is unfortunate that it didn't solve the case at all.
Now I am totally clueless and I don't know how to solve it.
I am not going to integrate 3rd party APIs as that's not how an open-source project works. And I have other things to do in life too, so I don't know when there will be any next update to the script.
If anyone wants to suggest some way out, you're welcome!

**Comment by wtfyo** [comment]
Having the same issue with my own PHP and cURL implementation. I am sending the cookie that is set by tik tok when I get the data from the video page. Not sure what else can be done. I've checked other repos that use python and it all looks similar. I'm going to keep trying. I'll provide an update if I find something.

**Comment by wtfyo** [comment]
I made some progress but getting a file unsupported error. Basically the headers sent for the original request for the video data must be the exact same headers sent.

The video downloads as an mp4 but when I try to open the file I get unsupported filetype error.

![image](https://user-images.githubusercontent.com/73618487/97509745-80494000-1959-11eb-904d-ba5ca093ada6.png)

**Comment by wtfyo** [comment]
Got it. There was a problem with my cURL options. So just make sure the headers sent in the initial request for the data related to the video is the same as the request for the video itself.

**Comment by TufayelLUS** [comment]
@wtfyo , could you please help me with your solution? I am not getting time to focus on this as I work in the marketplaces as a freelancer and rarely getting spare time to sit and fix it by spending a long time. Your contribution will be welcomed.

**Comment by TufayelLUS** [comment]
The script is now updated and it should start downloading videos again.
