### ISSUE TITLE
URL can't fetch

### ISSUE THREAD

**Issue by ikamal7** [TufayelLUS/TikTok-Video-Downloader-PHP#27]
tiktok new updated copy url not working ex. **https://vm.xzcs3zlph.com/ZSJun3C9J/** 
This type of URL not working.

**Comment by llacb47** [comment]
How did you get this URL? Do u use tiktok on ios or android? In what country do u live?

**Comment by ikamal7** [comment]
> How did you get this URL? Do u use tiktok on ios or android? In what country do u live?

I get it from the android app. Go to the app then Share icon and copy the link.

**Comment by llacb47** [comment]
I ask this because I think this type of share url (with the strange domain) only happens if you live in a country or have an ISP that tries to restrict tiktok's domains.

**Comment by TufayelLUS** [comment]
Hi, can you try regular URLs otherwise? Short URLs often display captcha before redirecting you to the actual content page and when there's a captcha, the actual page cannot be accessed until it is solved. So, it is recommended to use regular URLs other than short URLs like the one you mentioned. Thank you.
