### ISSUE TITLE
Getting an html file instead of the video

### ISSUE THREAD

**Issue by ErbWorks** [TufayelLUS/TikTok-Video-Downloader-PHP#34]

**Comment by TufayelLUS** [comment]
Hi, sometimes it may get blocked due to ReCaptcha triggering. I tried with an old video link, it seems to be working fine even today as well. Since there is no background proxy service running while making this request, my server often gets caught by captcha and it can stop working only at that time. My project isn't sponsored by anyone, so, do not expect anything fancy out of it.
